CREATE TABLE IF NOT EXISTS RESOURCE_BUNDLE_K
(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   RESOURCE_KEY VARCHAR (250) NOT NULL,
   DEFAULT_LOCALE VARCHAR (5) NOT NULL
);


CREATE TABLE IF NOT EXISTS  RESOURCE_BUNDLE_V
(
   ID INT AUTO_INCREMENT PRIMARY KEY,
   RESOURCE_BUNDLE_KEY_ID INT,
   LOCALE VARCHAR (5) NOT NULL,
   MSG_VALUE VARCHAR (1000) NOT NULL
);